---
title: "Curs d'estadística en R"
subtitle: "Classe 0: Introducció"
author: "Eudald Correig Fraga"

date: "`r format(Sys.time(), '%d de %B de %Y')`"
output: ioslides_presentation
---

# Estructura del curs

## Classe 0: Introducció

\bgroup
\hypersetup{linkcolor = red}
\listoffigures
\egroup

- Detalls del curs
- Descarregar i instal·lar R
- Descarregar i instal·lar RStudio
- Què és R
- Què és i com s'utilitza RStudio

## Classe 1: Introducció a R

- Objectes de R: vectors, matrius, llistes i dataframes

- Operacions en R

- Instal·lació de paquets i llibreries.

- Importació/ Exportació de dades.

- Operacions habituals de tractament de dades.

- Gràfics simples

## Classe 2: Markdown
- Markdown
- Espais de treball

## Classe 3: Estadística bàsica
- Test d'hipòtesi
- Implementació en R

## Classe 4: Errors i missings
- Identificació i tractament d'errors
- Identificació i tractament de missings


## Classe 5: Models predictius
- Regressió lineal
- Regressió logística
- Avaluació de models
- Corbes ROC i AUC

## Classe 6: Selecció de model
- Bias-variance tradeoff
- Overfitting i underfitting
- Forward subset selection
- Lasso

## Classe 7: Gràfics
- Utilització de ggplot2

## Classe 8: TBD

#  Classe 0: Introducció

# Bibliografia

## Introducció a R i tidyverse

> Hadley Wickham & Garrett Grolemund, R for Data Science. O'Reilly Media, 2017.  [https://r4ds.had.co.nz/](https://r4ds.had.co.nz/)

> Hadley Wickham, Romain François, Lionel Henry & Kirill Müller. dplyr: A Grammar of Data Manipulation. R package version 1.1.3. [https://dplyr.tidyverse.org/](https://dplyr.tidyverse.org/)

> Kuhn, Max and Silge, Julia. Hands-On Machine Learning with R. O'Reilly Media, 2019. [https://bradleyboehmke.github.io/HOML/](https://bradleyboehmke.github.io/HOML/)

> Hadley Wickham, Danielle Navarro & Thomas Lin Pedersen. ggplot2: Elegant Graphics for Data Analysis. Springer, 2016. [https://ggplot2-book.org/](https://ggplot2-book.org/)

## Introducció a Tests d'Hipòtesi

> Chester Ismay & Albert Y. Kim. Statistical Inference via Data Science: A ModernDive into R and the Tidyverse, 2nd Edition. CRC Press, 2024. [https://moderndive.com/v2/](https://moderndive.com/v2/)

> Simon P. Couch, Andrew P. Bray, Chester Ismay, Evgeni Chasnovski, Benjamin S. Baumer & Mine Çetinkaya-Rundel. infer: An R package for tidyverse-friendly statistical inference. R package version 1.0.7.  
> [https://infer.netlify.app/](https://infer.netlify.app/)

> Måns Thulin. Modern Statistics with R: From Wrangling and Exploring Data to Inference and Predictive Modelling, 2nd Edition. Chapman & Hall/CRC, 2024. [https://modernstatisticswithr.com/](https://modernstatisticswithr.com/)

> Max Kuhn & Julia Silge. Tidy Modeling with R. O'Reilly Media, 2022. [https://www.tmwr.org/](https://www.tmwr.org/)

## Models Predictius i Machine Learning

> Gareth James, Daniela Witten, Trevor Hastie & Robert Tibshirani. An Introduction to Statistical Learning: with Applications in R, 2nd Edition. Springer, 2021. [https://www.statlearning.com/](https://www.statlearning.com/)

> Trevor Hastie & Robert Tibshirani. Statistical Learning MOOC: 15 hours of expert videos.   [https://www.r-bloggers.com/in-depth-introduction-to-machine-learning-in-15-hours-of-expert-videos/](https://www.r-bloggers.com/in-depth-introduction-to-machine-learning-in-15-hours-of-expert-videos/)

> Max Kuhn & Julia Silge. Tidy Modeling with R. O'Reilly Media, 2022.   [https://www.tmwr.org/](https://www.tmwr.org/)

> Måns Thulin. Modern Statistics with R: From Wrangling and Exploring Data to Inference and Predictive Modelling, 2nd Edition. Chapman & Hall/CRC, 2024. [https://modernstatisticswithr.com/](https://modernstatisticswithr.com/)

## Fi

\center
\Large

Final de la classe 0.




